; 14-Ordenar un vector(8 BITS) (DE MEN A MAY SIN SIGNO) (de $00 a $FF)

; CONSTANTES
RAM			EQU		$0000
ROM			EQU		$8000

; VARIABLES
			ORG		RAM
DIR_INI			RMB		2
DIR_FIN			RMB		2
HUBO_INTERCAMBIO	RMB		1

; CODIGO
			ORG		ROM
BUCLE
			LDX		DIR_INI
			CPX		DIR_FIN
			BEQ		FUERA_BUCLE
			CLR		HUBO_INTERCAMBIO
BUCLE_INTERNO
			LDD		0,X
			CBA						; A-B. SI N=0 A>B
;			BPL		INTERCAMBIAR			; ? N = 0
;			BGE		INTERCAMBIAR			; ? N (+) V = 0				
;			BGT		INTERCAMBIAR			; ? Z + (N (+) V) = 0
;			BLE		INTERCAMBIAR			; ? Z + (N (+) V) = 1
			BHI		INTERCAMBIAR			; ? C + Z = 0  (ORDENA DE < A > SIN SIGNO)
SIG
			INX			
			CPX		DIR_FIN				; SI X=DIR_FIN -> Z=1
			BNE		BUCLE_INTERNO
			TST		HUBO_INTERCAMBIO		; HUBO_INTERCAMBIO=0
			BEQ		FUERA_BUCLE
			LDY		DIR_FIN
			DEY
			STY		DIR_FIN				; EN LA ULTIMA POS QUEDA EL MAYOR 
			BRA		BUCLE
FUERA_BUCLE
FIN			BRA		FIN

INTERCAMBIAR		
			STAA		1,X				; A->M+1
			STAB		0,X				; B->M
			INC		HUBO_INTERCAMBIO
			BRA		SIG



; INICIALIZACION DE VARIABLES
			ORG		DIR_INI
			DW		$0010
			ORG		DIR_FIN
			DW		($0010+16-1)
			ORG		$0010
;			DB		$10,$50,$30,$80,$A0,$00,$40,$60,$20,$70,$90,$B0,$C0,$D0,$F0,$E0
			DB		$00,$10,$20,$30,$40,$50,$60,$70,$80,$90,$A0,$B0,$C0,$D0,$E0,$F0
