; 16-Ordenar un vector(16 BITS)(DIR_INI Y DIR_FIN)

; CONSTANTES
RAM			EQU		$0000
ROM			EQU		$8000

; VARIABLES
			ORG		RAM
DIR_INI			RMB		2
DIR_FIN			RMB		2
HUBO_INTERCAMBIO	RMB		1
AUX			RMB		2

; CODIGO
			ORG		ROM
BUCLE
			LDX		DIR_INI
			CPX		DIR_FIN				; COMPARA (X=DIR_INI) CON DIR_FIN. SI SON IGUALES Z=1
			BEQ		FUERA_BUCLE			; ? Z = 1. AL SER DIR_INI == DIR_FIN, NO HAY NADA QUE ORDENAR Y SALE.
			CLR		HUBO_INTERCAMBIO
BUCLE_INTERNO
			LDD		0,X
			CPD		2,X				; D - (M : M + 1). 	SI N=0 (0,X)>(2,X)
;			BHS		INTERCAMBIAR			; ? C = 0  		(ORDENA DE < A > SIN SIGNO, IGUALES INTERCAMBIA)	
;			BHI		INTERCAMBIAR			; ? C + Z = 0  		(ORDENA DE < A > SIN SIGNO, IGUALES NO INTERCAMBIA)	
;			BGT		INTERCAMBIAR			; ? Z + (N (+) V) = 0	(ORDENA DE < A > CON SIGNO, IGUALES NO INTERCAMBIA)	
;			BGE		INTERCAMBIAR			; ? N (+) V = 0		(ORDENA DE < A > CON SIGNO, IGUALES INTERCAMBIA)	
;			BCS		INTERCAMBIAR			; ? C = 1  		(ORDENA DE > A < SIN SIGNO, IGUALES NO INTERCAMBIA)	
;			BLS		INTERCAMBIAR			; ? C + Z = 1  		(ORDENA DE > A < SIN SIGNO, IGUALES INTERCAMBIA)	
;			BLE		INTERCAMBIAR			; ? Z + (N (+) V) = 1	(ORDENA DE > A < CON SIGNO, IGUALES INTERCAMBIA)	
;			BLT		INTERCAMBIAR			; ? N (+) V = 1		(ORDENA DE > A < CON SIGNO, IGUALES NO INTERCAMBIA)	
SIG
			INX
			INX			
			CPX		DIR_FIN				; SI X=DIR_FIN -> Z=1
			BNE		BUCLE_INTERNO
			TST		HUBO_INTERCAMBIO		; TESTEA HUBO_INTERCAMBIO
			BEQ		FUERA_BUCLE			; ? Z = 1. SI EN TODA UNA RECORRIDA NO HUBO INTERCAMBIO, YA ESTA ORDENADO Y SALE.
			LDY		DIR_FIN
			DEY
			DEY
			STY		DIR_FIN				; EN LA ULTIMA POSICION YA QUEDO ORDENADO, Y POR ENDE SE RECORRE UNA MENOS.
			BRA		BUCLE
FUERA_BUCLE
FIN			BRA		FIN

									; EJEMPLO	0,X=B	2,X=A	D=B	AUX=0
INTERCAMBIAR		STD		AUX				; D->AUX	0,X=B	2,X=A	D=B	AUX=B
			LDD		2,X				; 2,X->D	0,X=B	2,X=A	D=A	AUX=0
			STD		0,X				; D->0,X	0,X=A	2,X=A	D=A	AUX=B
			LDD		AUX				; AUX->D	0,X=A	2,X=A	D=B	AUX=B
			STD		2,X				; D->2,X	0,X=A	2,X=B	D=B	AUX=B
			CLR		AUX				; AUX=00
			CLR		AUX+1				; AUX+1=00	0,X=B	2,X=A	D=B	AUX=0 (IDEM AL PPIO)
			TST		HUBO_INTERCAMBIO		; SE TESTEA PARA VER SI ESTA EN CERO
			BNE		SIG				; SI YA NO ESTA EN 0, SALE DE LA SUBRUTINA
			INC		HUBO_INTERCAMBIO		; DE 0 LO INCREMENTA A 1. NO SE INCREMENTA DIRECTAMENTE PORQUE 
			BRA		SIG				; SI SE INCREMENTARA 256 (O UNO DE ESOS MULTIPLOS), QUEDARIA EN $00.

; INICIALIZACION DE VARIABLES
			ORG		DIR_INI
			DW		$0010
			ORG		DIR_FIN
			DW		($0010-2)+16*2			; +"CANT DE ELEMENTOS"
			ORG		AUX
			DW		$0000

; CARGAR EL VECTOR
			ORG		$0010
			DW		$1000,$5000,$3000,$8000,$A000,$0000,$4000,$6000,$2000,$7000,$9000,$B000,$C000,$D000,$F000,$E000
;			DW		$0000,$1000,$2000,$3000,$4000,$5000,$6000,$7000,$8000,$9000,$A000,$B000,$C000,$D000,$E000,$F000
;			DW		$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
;			DW		$1000,$5000,$3000
;			DB		$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
;			DB		$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
